normalize image name
Portshift/kubei pull request #29
Opened 2020-08-30 20:40 UTC by Erezf-p

Resolve MAN-3917 , MAN-3915

2020-08-31 10:27 UTC, FrimIdan requested changes

2020-08-31 10:27 UTC, FrimIdan commented on pkg/scanner/scanner_test.go
> +}
EOL

2020-08-31 10:27 UTC, FrimIdan commented on pkg/scanner/scanner.go
> +	imageName           string
Is it being used?

2020-09-01 18:25 UTC, FrimIdan commented on pkg/scanner/scanner.go
> +		_ = k8s_utils.VisitContainersWithPath(&pod.Spec, func(container *corev1.Container, _ *field.Path) error {
You can create one slice from pod.Spec.Containers & pod.Spec.InitContainers and go over it - why the need to use `VisitContainersWithPath`?

2020-09-09 14:19 UTC, FrimIdan commented on go.mod
> +	k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
@Erezf-p do you still need this?

2020-09-12 17:31 UTC, Erezf-p commented on go.mod
> +	k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
no. will remove

2020-09-13 07:27 UTC, merged